### ISSUE TITLE
gdx release for students 2016 edition

### ISSUE THREAD

**Issue by RandomReaper** [hevs-isi/gdx2d#125]
Hello!

I just tested gdx2d-1.2.1.zip with our eclise mars.2 (mui 1.1) release.

Here are my remarks:
* 5 projects in the archive (a little bit confusing).
* in gdx2d-helloDesktop : project references java 1.6 library (only 1.8 in DRxx)
* in gdx2d-helloDesktop : The ant build file works as expected but warns about missing java 1.6

**Comment by pmudry** [comment]
I don't like the idea of 5 projects either. 

@metc Can we do something about it ? 

In addition, #124 relates to the same issues.

**Comment by metc** [comment]
By `gdx2d-1.2.1.zip`, you mean the archive of the gt `master` branch ?

1. Remark 1) The students only need two projects: they need the `gdx2d-demoDesktop` to look at the demo source files and get some inspiration, and the `gdx2d-helloDesktop` as a bootstrap project to start coding. These two projects can be build using `ant`. The `gdx2d-library` is a Maven project (with sub modules) and should not be used by the students.

2. Remarks 2) and 3) `gdx2d` is compatible from Java SE 1.6 and up. The warning message is correct, since the installed JDK does not match with the generated bytecode version. Travis CI build the library using 4 different JDK without error. We should discuss if we still want to target 1.6 and 1.7 or not.

**Comment by RandomReaper** [comment]
I got the release from the documentation page, but @pmudry has modified that link today, not really sure what it means.

For the students, I think we should only provide an importable archive, containing ```gdx2d-demoDesktop``` and ```gdx2d-helloDesktop```.

And for this archive (and only here at this time) reference java 1.8.

**Comment by metc** [comment]
@RandomReaper agree.

**Comment by metc** [comment]
We can attach custom files to any release on Github, see https://github.com/hevs-isi/gdx2d/releases/tag/v1.2.1. `gdx2d-demoDesktop` and `gdx2d-helloDesktop` are standalone projects, so the library project can be removed for the students.

Should I prepare the Zip file for the students ?

**Comment by pmudry** [comment]
that would be perfect !

**Comment by metc** [comment]
The students zip file can be downloaded from here: https://github.com/hevs-isi/gdx2d/releases/tag/v1.2.1

I will create a script to generate it automatically.

**Comment by pmudry** [comment]
I just added a static link on the documentation webpage to help the students get it directly. Is there any way to automate this ?

**Comment by metc** [comment]
The student Zip file is currently hosted on Github. IMO the easiest solution is to change the link manually when required, since we also have to add a news when a new release is available.

If you really want to automate the process, we could use the [Github API](https://developer.github.com/v3/repos/pages/) to get the release links automatically.

**Comment by pmudry** [comment]
No it's okay like this

**Comment by pmudry** [comment]
Thank you !
