### ISSUE TITLE
sitemap.xml is wrong

### ISSUE THREAD

**Issue by RandomReaper** [hevs-isi/gdx2d#154]
e1b9baa1f80f184333e8816bfb0449f8b4731745 fixed the documentation fail to update, but sitemap.xml is wrong.
Possible solution : disable sitemap.xml generation, google is smart enough.

**Comment by metc** [comment]
I have figured out what the problem was. It was hard to find because the local build is green.

The dates of all the pages of the `doc` collection were wrong. If fact, when building locally, the build date of the site was displayed instead. You can solve the Github build issue by:

1. Adding a `date:` attribute for each pages inside the `_doc` folder to indicates the latest update (the header of each page from the `doc` collection has to be updated)
2. In the sitemap file you could replace `p.date | date_to_xmlschema` by `site.time | date_to_xmlschema` and assuming that the modification date of each page is the same as the site date
3. Or as you suggested just remove the sitemap (and update the `robots.txt` file)
