### ISSUE TITLE
setPixel method is slow

### ISSUE THREAD

**Issue by metc** [hevs-isi/gdx2d#26]
The current `setPixel` use a `ShapeRenderer` and that is slow.

Why not use a `Pixmap` ?

**Comment by RandomReaper** [comment]
I have digged into the code and found some reasons `setPixel` is slow:
* every drawing function ends then begins a new `ShapeRenderer`
* `setPixel` calls `shaperenderer.identity()` on each call.

I've done some tests removing identity() and not re-initializing the `ShapeRenderer` when not changing mode, it is something like 30x faster :smile:

I don't want to commit that changes because I don't really understand why the `ShapeRenderer` is initialized in the `clear()` function and seems to be ended in the next image drawn...

**Comment by pmudry** [comment]
ShapeRenderers internally use glBegin/glEnd. If you don't take care, you
could end up with a glBegin following a glBegin which makes the GL stack
crash. If you do something wrong, you'll notice it, so hack happily!

**Comment by pmudry** [comment]
done
