### ISSUE TITLE
glBegin / glEnd changes cause problem

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/gdx2d#90]
problem with glBegin

**Comment by RandomReaper** [comment]
ack

**Comment by RandomReaper** [comment]
Problem introduced by me in b9debce018b3e11481f03c0184af2100edf72b67.
I can restore the previous behavior, but in any way mixing spritebatch with setPixel will crash

g.spriteBatch.draw
g.setPixel
g.spriteBatch.draw <- crash (as before b9debce018b3e11481f03c0184af2100edf72b67).

It will crash because setpixel will change the rendering mode to  `t_rendering_mode.SHAPE_POINT`.

**Comment by pmudry** [comment]
FPS and logo are no longer rendered correctly because of this change (try any `DemoShaderXXX`). Sorry

**Comment by RandomReaper** [comment]
Ooops I missed that :smile:
